
def rgb(*colour):
    return "#%02x%02x%02x" % colour 


# GENERAL

JOYSTICK = False #are we using a joystick?

COLOUR_GREEN = '#90c73e'
COLOUR_RED = '#f2644d'


BACKGROUND_COLOUR = 'lightgray'
OUTLINE_WIDTH = 2
OUTLINE_COLOUR = 'black'

MAIN_BANNER_COLOUR = '#0000fe'
MAIN_BANNER_HEIGHT = 16

#SYSTEM MONITOR
SYSTEM_MONITOR_HEIGHT = 400
SYSTEM_MONITOR_WIDTH = 400

SYSTEM_MONITOR_SCALE_BACKGROUND_COLOUR = '#add9e6'
SYSTEM_MONITOR_SCALE_BACKGROUND_COLOUR_FILL = '#4882b2'
SYSTEM_MONITOR_SCALE_POSITIONS = [0,1,2,3] #this can be random...

#TRACKING MONITOR
TRACKING_LINE_COLOUR = '#268fea'
TRACKING_TARGET_SPEED = 4


#FUEL MONITOR
FUEL_MONITOR_WIDTH = 800
FUEL_MONITOR_HEIGHT = 400

FUEL_TANK_LINE_THICKNESS = 2
FUEL_TANK_LINE_COLOUR = 'black'


PUMP_HEIGHT = 20
PUMP_WIDTH = 40
