################################# Default configuration ###################
baseURL = "https://dicelab-rhul.github.io/ICU/"
title = "Integrated Cognitive User Assistance (ICU)"
theme = "airspace-hugo"
# post pagination
paginate = "1"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
publishDir = "docs"

################################# Outputs #################################
# hugo outputs
[outputs]
home = [ "HTML", "RSS"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 1


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logorhul = "images/rhul-logo.png"
logoEPSRC = "images/EPSRC.png"
logoHLC = "images/HLC_AI.png"
# Meta data
description = "Integrated Cognitive User Assistance (ICU)"
author = "Themefisher"
# Contact Information
mobile = "TODO"
email = "TODO"
location = "London UK"
# Google Analitycs
google_analitycs_id = "" # Your ID# search

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"


  
############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = ""
weight = 1

[[Languages.en.menu.main]]
name = "Team"
URL = "team"
weight = 2

[[Languages.en.menu.main]]
name = "Documentation"
URL = "documentation"
weight = 3

[[Languages.en.menu.main]]
name = "Download"
URL = "download"
weight = 4


# footer menu
[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 1


