COLOR_GREEN = '#90c73e'
COLOR_RED = '#f2644d'
COLOR_GREY = 'lightgray'
COLOR_BLACK = 'black'
COLOR_BLUE = '#255f9e'
COLOR_LIGHT_BLUE = '#92c6d9'

LINE_DASH_LENGTH = 10
LINE_WIDTH = 2
LINE_COLOR = "BLACK"
PADDING = 0.05

# constants for the system task
WARNINGLIGHT1 = "WARNINGLIGHT1"
WARNINGLIGHT2 = "WARNINGLIGHT2"
SLIDER = "SLIDER{}"
SLIDERBOX = "SLIDERBOX{}"
SYSTEMTASK = "SYSTEMTASK"
WARNING_LIGHT_SIZE = (1/3, 1/5)
NUM_SLIDERS = 4
NUM_SLIDER_STEPS = 11


# constants for the tracking task
TRACKINGTASK = "TRACKINGTASK"
TRACKING_LINE_COLOUR = '#268fea'
TRACKING_LINE_WIDTH = 4
TARGET1 = "TARGET"

# constants for the fuel task
FUELTANKMAIN_CAPACITY = 2000
FUELTANKLEFT_CAPACITY = 1000
FUELTANKRIGHT_CAPACITY = 1500
FUELTANKMAIN_FAILURE_INTERVAL = (1/2 - 0.1, 1/2 + 0.1)
# cosmetic
FUELTANKMAIN_FUEL_LEVEL_PROTRUSION = 6