
def rgb(*colour):
    return "#%02x%02x%02x" % colour 

JOYSTICK = False #are we using a joystick?


BACKGROUND_COLOUR = 'lightgray'
OUTLINE_WIDTH = 2
OUTLINE_COLOUR = 'black'

#system monitor
SYSTEM_MONITOR_HEIGHT = 500
SYSTEM_MONITOR_WIDTH = 400

SYSTEM_MONITOR_SCALE_BACKGROUND_COLOUR = '#add9e6'
SYSTEM_MONITOR_SCALE_BACKGROUND_COLOUR_FILL = '#4882b2'
SYSTEM_MONITOR_SCALE_POSITIONS = [0,1,2,3] #this can be random...

MAIN_BANNER_COLOUR = '#0000fe'
MAIN_BANNER_HEIGHT = 20

TRACKING_LINE_COLOUR = '#268fea'
TRACKING_TARGET_SPEED = 4
